export const leftSidebarData = [
  {
    title: 'Genres',
    items: [
      'Action',
      'Romance',
      'Fantasy',
      'Mystery',
      'Horror',
      'Sci-Fi',
      'Slice of Life',
      'Drama',
      'Comedy',
      'Thriller',
      'Historical',
    ],
  },
  {
    title: 'Categories',
    items: [
      'Kinetic Novels',
      'Branching Novels',
      'Dating Simulation',
      'Mystery/Detective Novels',
      'Otome Games',
      "BL (Boys' Love)",
      "GL (Girls' Love)",
      'Eroge (Adult Visual Novels)',
      'Adventure Visual Novels',
      'Horror Visual Novels',
      'Slice-of-Life Visual Novels',
      'Fantasy Visual Novels',
      'Comedy Visual Novels',
    ],
  },

  {
    title: 'Tags',
    items: [
      'Completed',
      'Ongoing',
      'English',
      'Japanese',
      'Voice Acting',
      'Multiple Endings',
      'Free to Play',
    ],
  },
];

export const rightSidebarData = [
  {
    title: 'Top Rated',
    items: [
      'Visual Novel A',
      'Visual Novel B',
      'Visual Novel C',
      'Visual Novel D',
      'Visual Novel E',
    ],
  },
  {
    title: 'Newest Releases',
    items: ['New Release 1', 'New Release 2', 'New Release 3', 'New Release 4'],
  },
  {
    title: 'Most Popular',
    items: ['Popular VN 1', 'Popular VN 2', 'Popular VN 3', 'Popular VN 4'],
  },
  {
    title: 'Recommendations',
    items: [
      'Recommended VN 1',
      'Recommended VN 2',
      'Recommended VN 3',
      'Recommended VN 4',
    ],
  },
];

export const bannerData = [
  {
    name: 'Angel Beats',
    image1: '/src/assets/images/RecommendedBanner/AngelBeats/image1.png',
    image2: '/src/assets/images/RecommendedBanner/AngelBeats/image2.png',
    image3: '/src/assets/images/RecommendedBanner/AngelBeats/image3.png',
    description:
      'Angel Beats! is set in the environment of a high school in the afterlife, a type of limbo for people who have experienced trauma or hardships in life and must overcome them before passing on and being reincarnated. The story follows Yuzuru Otonashi, a boy with amnesia who ends up in the afterlife.',
  },
  {
    name: 'When They Cry',
    image1: '/src/assets/images/RecommendedBanner/AngelBeats/image1.png',
    image2: '/src/assets/images/RecommendedBanner/AngelBeats/image2.png',
    image3: '/src/assets/images/RecommendedBanner/AngelBeats/image3.png',
    description:
      'Angel Beats! is set in the environment of a high school in the afterlife, a type of limbo for people who have experienced trauma or hardships in life and must overcome them before passing on and being reincarnated. The story follows Yuzuru Otonashi, a boy with amnesia who ends up in the afterlife.',
  },
];

export const genresSliderData = [
  {
    title: 'Action',
    imgPath: '/src/assets/images/Genres/Action.png',
  },
  {
    title: 'Romance',
    imgPath: '/src/assets/images/Genres/Romance.png',
  },
  {
    title: 'Sci-Fi',
    imgPath: '/src/assets/images/Genres/Sci-Fi.png',
  },
  {
    title: 'Fantasy',
    imgPath: '/src/assets/images/Genres/Fantasy.png',
  },
  {
    title: 'Slice of Life',
    imgPath: '/src/assets/images/Genres/SliceOfLIfe.png',
  },
  {
    title: 'Comedy',
    imgPath: '/src/assets/images/Genres/Comedy.png',
  },
  {
    title: 'Historical',
    imgPath: '/src/assets/images/Genres/Historical.png',
  },
  {
    title: 'Thriller',
    imgPath: '/src/assets/images/Genres/Thriller.png',
  },
  {
    title: 'Horror',
    imgPath: '/src/assets/images/Genres/Horror.png',
  },
];

export const animes = [
  {
    id: '1',
    name: 'Steins Gate',
    imagePath: '/src/assets/images/TopRated/Steins.jpg',
  },
  {
    id: '2',
    name: 'Clannad',
    imagePath: '/src/assets/images/TopRated/Clannad.jpg',
  },
  {
    id: '3',
    name: 'Dragonronpa',
    imagePath: '/src/assets/images/TopRated/Dragonronpa.png',
  },
  {
    id: '4',
    name: 'The House in Fata Morgana',
    imagePath: '/src/assets/images/TopRated/House.jpg',
  },
  {
    id: '5',
    name: 'Fate',
    imagePath: '/src/assets/images/TopRated/Fate.jpg',
  },
  {
    id: '6',
    name: 'When They Cry',
    imagePath: '/src/assets/images/TopRated/Higurashi.jpg',
  },
];

export const newsData = [
  {
    imagePath: '/src/assets/images/News/news1.jpg', // Placeholder for image path
    date: '2024-11-30',
    text: 'Spike Chunsoft has officially confirmed the release of the fan-favorite visual novel "Anonymous;Code" on Steam, set for 2024. Fans of the Science Adventure series can look forward to an intricate, hacker-themed narrative.',
    title: 'Anonymous;Code Announced for Steam in 2024',
  },
  {
    imagePath: '/src/assets/images/News/news2.jpg', // Placeholder for image path
    date: '2024-11-28',
    text: 'The classic visual novel "Steins;Gate" celebrates its 15th anniversary with a new collector’s edition release, including exclusive art and behind-the-scenes content, delighting long-time fans of the series.',
    title: 'Steins;Gate 15th Anniversary Edition Released',
  },
  {
    imagePath: '/src/assets/images/News/news3.jpg', // Placeholder for image path
    date: '2024-11-25',
    text: 'Frontwing has revealed a new project titled "Ginka," an original fantasy visual novel. Set to release in Spring 2024, it promises an emotional tale with beautifully crafted visuals and a compelling story.',
    title: 'Frontwing Announces New Visual Novel "Ginka"',
  },
  {
    imagePath: '/src/assets/images/News/news4.jpg', // Placeholder for image path
    date: '2024-11-22',
    text: 'The critically acclaimed visual novel "The House in Fata Morgana" has been added to Xbox Game Pass, making it more accessible to a wider audience. Known for its gothic atmosphere, it is one of the highest-rated visual novels.',
    title: 'The House in Fata Morgana Joins Xbox Game Pass',
  },
];

export const sampleNovels = [
  {
    imagePath: '/src/assets/images/TopRated/Clannad.jpg',
    title: 'Clannad',
    date: '2024-12-03',
    description:
      'Clannad takes you on a journey through the daily life of Tomoya Okazaki, a high school delinquent who hides from his troubled past. His encounter with Nagisa Furukawa, a clumsy girl struggling to continue school after illness, sparks a connection that leads Tomoya to slowly rediscover the joy in life. As he befriends various characters, each with their own stories, the narrative weaves between heartfelt moments and quirky, comedic scenes. Yet, lurking beneath the surface is a mysterious and fantastical story about a doll and a girl trapped in a world where nothing ever changes. The paths you choose will lead to different resolutions, some grounded in reality, others touched by the supernatural. As you become more involved with the characters, the drama deepens—culminating in an emotional journey with After Story, an unforgettable conclusion that will stay with you. Will you uncover the secrets of the hidden story, or will you focus on the emotional bonds Tomoya forms with those around him? One thing’s for sure: Clannad offers an experience that will both challenge and tug at your heartstrings. Are you ready to uncover its mysteries?',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Key',
  },

  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '2',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '3',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '4',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '5',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '6',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '7',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '8',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '9',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '10',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '11',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '1',
    date: '2024-12-03',
    description: 'amogus',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '2',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '3',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '4',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '5',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '6',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '7',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '8',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '9',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '10',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny.',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
  {
    imagePath: '/src/assets/images/Genres/Action.png',
    title: '11',
    date: '2024-12-03',
    description: 'An epic tale of love and destiny. ',
    rating: 9.5,
    genre: 'Fantasy',
    type: 'Visual Novel',
    duration: '10-20 hours',
    author: 'Studio XYZ',
  },
];
